### PR TITLE
Fixed Typo from "Baidu Dick" to "Baidu Disk"

### PR DESCRIPTION
**Pull request by amogh-ajnalens**

### CODE REVIEW

**Comment by initialneil** [comment]
cool

**Comment by richdrummer33** [comment]
The most pivotal hotfix in the history of commits made across all commits ever made ever

**Comment by amogh-ajnalens** [comment]
Finally!! I was worried that the whole reputation of the project hinged upon that typo. Now we can all rest easy. 😌

**Comment by adityaatajna** [comment]
A detailed change description will be added to the company history books to commemorate this momentous occasion.

**Comment by initialneil** [comment]
I blame Microsoft Editor for this.
If I had used Grammarly...
OK, I blame Grammarly for this too.

**Pull request merged**
